# -*- coding: utf-8 -*-
"""st3247assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ymZtTv7bIHNhUzjEamfF-4MvPJ6JooH
"""

#Set working directory as needed
#import os
#os.chdir("/content/sample_data")

#Install packages
#!pip install pandas numpy scikit-optimize seaborn matplotlib scikit-learn joblib numba corner

## IMPORT ALL PACKAGES NEEDED
import numpy as np
import pandas as pd
import skopt
import seaborn as sns
import matplotlib.pyplot as plt
from numba import njit
import numba
import corner
import joblib
from joblib import Parallel, delayed
from sklearn.linear_model import LinearRegression
from skopt import Optimizer
from skopt.learning import GaussianProcessRegressor
from skopt.learning.gaussian_process.kernels import Matern
np.random.seed(3247)

## DEFINE THE SIMULATOR FUNCTION
"""
Adaptive-network SIR epidemic simulator — Numba-accelerated version.

Key design changes for Numba compatibility
------------------------------------------
The original code used Python sets for the adjacency list (neighbors[i]).
Numba's @njit cannot work with Python sets or variable-length lists of sets.
We therefore re-represent the graph as a DENSE adjacency matrix:

    adj : np.ndarray, shape (N, N), dtype np.bool_
    adj[i, j] == True  ⟺  edge (i, j) exists

Memory cost: 200×200×1 byte = 40 KB — negligible.
Lookup cost: O(1) (array index vs. hash table lookup in a set, but with no
             Python interpreter overhead inside the JIT-compiled function).

Degree bookkeeping: we maintain a separate `degree` array (shape N, int32)
to avoid calling np.sum(adj[i]) repeatedly inside the hot loop.

Random numbers: Numba supports numpy.random functions natively inside @njit;
we use numpy.random.random(), numpy.random.randint() etc.  The outer caller
sets np.random.seed(seed) before each call so results are reproducible.

Reference: Gross et al. (2006), PRL 96, 208701.
"""


# ── Core simulation (JIT-compiled, no Python objects) ───────────────────────────
@njit(cache=True)
def _simulate_numba(beta, gamma, rho, N, p_edge, n_infected0, T, seed):
    """
    JIT-compiled inner loop for the adaptive-network SIR model.

    Uses a dense boolean adjacency matrix instead of Python sets so that
    Numba can compile the function to native machine code.

    Parameters
    ----------
    beta, gamma, rho : float
        Transmission, recovery, and rewiring probabilities.
    N : int
        Population size (number of nodes).
    p_edge : float
        Initial Erdos-Renyi edge probability.
    n_infected0 : int
        Number of initially infected nodes.
    T : int
        Number of time steps.
    seed : int
        Seed for numpy.random (set inside the JIT function for thread safety).

    Returns
    -------
    infected_fraction : float64 array, shape (T+1,)
    rewire_counts     : int64   array, shape (T+1,)
    degree_histogram  : int64   array, shape (31,)
    """
    np.random.seed(seed)

    # ── Adjacency matrix & degree array ─────────────────────────────────────
    # adj[i, j] = True means an edge exists between i and j (undirected).
    # degree[i] caches len(neighbors[i]) to avoid recomputing it each step.
    adj    = np.zeros((N, N), dtype=np.bool_)
    degree = np.zeros(N, dtype=np.int32)

    # Build Erdos-Renyi graph
    for i in range(N):
        for j in range(i + 1, N):
            if np.random.random() < p_edge:
                adj[i, j] = True
                adj[j, i] = True
                degree[i] += 1
                degree[j] += 1

    # ── Initial states ───────────────────────────────────────────────────────
    # 0 = Susceptible, 1 = Infected, 2 = Recovered
    state = np.zeros(N, dtype=np.int8)

    # Sample n_infected0 distinct initial seeds via Fisher-Yates partial shuffle
    perm = np.arange(N)
    for k in range(n_infected0):
        r = k + np.random.randint(0, N - k)
        perm[k], perm[r] = perm[r], perm[k]
        state[perm[k]] = 1

    # ── Output arrays ────────────────────────────────────────────────────────
    infected_fraction = np.zeros(T + 1, dtype=np.float64)
    rewire_counts     = np.zeros(T + 1, dtype=np.int64)

    # Count initial infected fraction
    init_inf = 0
    for i in range(N):
        if state[i] == 1:
            init_inf += 1
    infected_fraction[0] = init_inf / N

    # ── Main loop ────────────────────────────────────────────────────────────
    # Temporary arrays reused each step to avoid heap allocations.
    # We over-allocate to the worst-case size; actual length tracked separately.
    new_inf_buf  = np.empty(N,      dtype=np.int32)   # newly infected nodes
    si_s_buf     = np.empty(N * 30, dtype=np.int32)   # S endpoint of S-I edges
    si_i_buf     = np.empty(N * 30, dtype=np.int32)   # I endpoint of S-I edges
    cand_buf     = np.empty(N,      dtype=np.int32)   # rewiring candidates

    for t in range(1, T + 1):

        # ── Phase 1: Infection (synchronous) ────────────────────────────────
        n_new = 0
        for i in range(N):
            if state[i] == 1:                          # i is infected
                for j in range(N):
                    if adj[i, j] and state[j] == 0:    # S-I edge
                        if np.random.random() < beta:
                            # Stage the infection; do not mutate state yet
                            new_inf_buf[n_new] = j
                            n_new += 1

        # Apply staged infections (may include duplicates — that is fine;
        # setting state to 1 twice is idempotent).
        for k in range(n_new):
            state[new_inf_buf[k]] = 1

        # ── Phase 2: Recovery ────────────────────────────────────────────────
        for i in range(N):
            if state[i] == 1:
                if np.random.random() < gamma:
                    state[i] = 2

        # ── Phase 3: Rewiring ────────────────────────────────────────────────
        # Collect all current S-I edges first (snapshot before any rewiring).
        n_si = 0
        for i in range(N):
            if state[i] == 0:                          # i is susceptible
                for j in range(N):
                    if adj[i, j] and state[j] == 1:    # j is infected
                        si_s_buf[n_si] = i
                        si_i_buf[n_si] = j
                        n_si += 1

        rewire_count = 0
        for k in range(n_si):
            s_node = si_s_buf[k]
            i_node = si_i_buf[k]

            if np.random.random() >= rho:
                continue                               # edge not rewired

            # Edge may have been removed by an earlier rewiring this step
            if not adj[s_node, i_node]:
                continue

            # Remove the S-I edge
            adj[s_node, i_node] = False
            adj[i_node, s_node] = False
            degree[s_node] -= 1
            degree[i_node] -= 1

            # Build candidate list: all nodes not s_node and not already adjacent
            n_cand = 0
            for c in range(N):
                if c != s_node and not adj[s_node, c]:
                    cand_buf[n_cand] = c
                    n_cand += 1

            if n_cand > 0:
                new_partner = cand_buf[np.random.randint(0, n_cand)]
                adj[s_node, new_partner] = True
                adj[new_partner, s_node] = True
                degree[s_node]       += 1
                degree[new_partner]  += 1
                rewire_count         += 1

        # ── Record statistics ────────────────────────────────────────────────
        n_inf = 0
        for i in range(N):
            if state[i] == 1:
                n_inf += 1
        infected_fraction[t] = n_inf / N
        rewire_counts[t]     = rewire_count

    # ── Final degree histogram ────────────────────────────────────────────────
    degree_histogram = np.zeros(31, dtype=np.int64)
    for i in range(N):
        d = degree[i]
        if d >= 30:
            degree_histogram[30] += 1
        else:
            degree_histogram[d]  += 1

    return infected_fraction, rewire_counts, degree_histogram


# ── Python wrapper (matches original API exactly) ───────────────────────────────
def simulate(beta, gamma, rho, N=200, p_edge=0.05, n_infected0=5, T=200, rng=None):
    """
    Run one replicate of the adaptive-network SIR model.

    This wrapper preserves the original function signature so that all
    downstream code (ABC workers, plotting, etc.) works without changes.
    Internally it calls _simulate_numba(), the JIT-compiled inner function.

    The `rng` argument is accepted for API compatibility but is not used;
    thread-safe seeding is handled inside the JIT function instead.

    Parameters
    ----------
    beta : float in [0, 1]     Transmission probability per S-I edge per step.
    gamma : float in [0, 1]    Recovery probability per infected node per step.
    rho : float in [0, 1]      Rewiring probability per S-I edge per step.
    N : int                    Number of nodes (default 200).
    p_edge : float             Erdos-Renyi edge probability (default 0.05).
    n_infected0 : int          Initially infected nodes (default 5).
    T : int                    Simulation length in steps (default 200).
    rng : ignored              Kept for backward compatibility only.

    Returns
    -------
    infected_fraction : np.ndarray, shape (T+1,)   Fraction infected at each step.
    rewire_counts     : np.ndarray, shape (T+1,)   Rewiring events at each step.
    degree_histogram  : np.ndarray, shape (31,)    Final degree histogram.
    """
    # Draw a 32-bit seed from numpy's global RNG so that passing rng=... from
    # the outer loop still propagates randomness (the outer rng object is not
    # used directly, but calling rng.integers ensures it advances correctly).
    if rng is not None:
        seed = int(rng.integers(0, 2**31))
    else:
        seed = int(np.random.randint(0, 2**31))
    return _simulate_numba(beta, gamma, rho, N, p_edge, n_infected0, T, seed)


# ── Warm up the JIT compiler ─────────────────────────────────────────────────────
# The first call to a @njit function triggers compilation (~5-30 s).
# We run a cheap warm-up here so the overhead does not count against the ABC loop.
print("Warming up Numba JIT compiler (compiles once, cached for future runs)…")
_ = simulate(0.2, 0.1, 0.3, N=200, T=5)   # tiny run just to trigger compilation
print("JIT compilation complete.  All subsequent calls will be fast.")

##READ DATA
infected_df = pd.read_csv("infected_timeseries.csv")
rewire_df   = pd.read_csv("rewiring_timeseries.csv")
degree_df   = pd.read_csv("final_degree_histograms.csv")

obs_inf = infected_df.groupby("time")["infected_fraction"].mean().values
obs_rew = rewire_df.groupby("time")["rewire_count"].mean().values
obs_deg = degree_df.groupby("degree")["count"].mean().values

##ABC RUN-1

# ==============================
# 2. SUMMARY STATISTICS
# ==============================
def compute_summary(inf_vec, rew_vec, deg_hist_vec):
    """
    Compute a fixed-length summary-statistic vector from one simulation
    (or from the observed data).

    Statistics chosen to capture different aspects of the epidemic:
      0  peak_inf    — maximum infected fraction (magnitude of outbreak)
      1  time_peak   — time step at which peak occurs (speed of outbreak)
      2  final_inf   — fraction still infected at t=T (residual burden)
      3  auc         — area under infected curve (total exposure)
      4  total_rew   — cumulative rewiring events (avoidance behavior)
      5  mean_deg    — mean final degree (network structure change)

    These six statistics together allow ABC to distinguish scenarios where,
    e.g., a low beta combined with high rho produces a similar peak_inf
    as a high beta with low rho, but different time_peak and total_rew.
    """
    peak_inf  = np.max(inf_vec)
    time_peak = np.argmax(inf_vec).astype(float)
    final_inf = inf_vec[-1]
    auc       = np.sum(inf_vec)
    total_rew = float(np.sum(rew_vec))

    degrees  = np.arange(len(deg_hist_vec))
    mean_deg = np.sum(degrees * deg_hist_vec) / max(np.sum(deg_hist_vec), 1.0)


    return np.array([peak_inf, time_peak, final_inf, auc, total_rew, mean_deg])

obs_summary = compute_summary(obs_inf, obs_rew, obs_deg)

# ==============================
# 3. ABC WORKER
# ==============================
def abc_worker(seed):
    """
    Draw one parameter sample from the prior, simulate, and return
    [beta, gamma, rho, s0, s1, s2, s3, s4, s5] where s_i are summary stats.

    This function is called inside joblib's Parallel; the Numba-compiled
    _simulate_numba is already compiled when we reach this point, so there
    is no per-worker compilation overhead.
    """
    rng  = np.random.default_rng(seed)

    beta  = rng.uniform(0.05, 0.50)
    gamma = rng.uniform(0.02, 0.20)
    rho   = rng.uniform(0.00, 0.80)

    sim_inf, sim_rew, sim_deg = simulate(beta, gamma, rho, rng=rng)
    sim_sum = compute_summary(sim_inf, sim_rew, sim_deg)

    return [beta, gamma, rho, *sim_sum]

# ==============================
# 4. RUN PARALLEL ABC
# ==============================
N_SAMPLES    = 100_000   # 100 k recommended; increase to 500 k for finer posteriors
ACCEPT_RATIO = 0.01      # keep best 1 %

print(f"Starting {N_SAMPLES:,} simulations (Numba-accelerated)…")
seeds = np.random.randint(0, 2**31, size=N_SAMPLES)

results_raw = Parallel(n_jobs=-1, verbose=5)(
    delayed(abc_worker)(s) for s in seeds
)

results_raw      = np.array(results_raw)
all_params       = results_raw[:, :3]
all_sim_summaries = results_raw[:, 3:]

# ==============================
# 5. STANDARDISED DISTANCE
# ==============================
# Divide each summary statistic by its across-simulation standard deviation
# so that all six statistics contribute equally to the Euclidean distance.
stat_scales = np.std(all_sim_summaries, axis=0)
stat_scales[stat_scales == 0] = 1.0          # guard against constant stats

diffs     = (all_sim_summaries - obs_summary) / stat_scales
distances = np.sqrt(np.sum(diffs**2, axis=1))

# ==============================
# 6. SELECTION
# ==============================
k               = int(ACCEPT_RATIO * N_SAMPLES)
sorted_indices  = np.argsort(distances)
accepted_idx    = sorted_indices[:k]
accepted_params = all_params[accepted_idx]

print(f"\nAccepted {len(accepted_params):,} samples.")
print(f"Best distance : {distances[sorted_indices[0]]:.4f}")
print(f"Threshold dist: {distances[sorted_indices[k-1]]:.4f}")
print(f"\nPosterior medians  — beta: {np.median(accepted_params[:,0]):.4f}  "
      f"gamma: {np.median(accepted_params[:,1]):.4f}  "
      f"rho: {np.median(accepted_params[:,2]):.4f}")

##ABC Run 1 Posteriors
# 7. PLOT POSTERIORS
# ==============================
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
param_names = ["β (beta)", "γ (gamma)", "ρ (rho)"]
colors      = ["steelblue", "coral", "mediumseagreen"]

for i in range(3):
    ax = axes[i]
    ax.hist(accepted_params[:, i], bins=40,
            color=colors[i], edgecolor="white", linewidth=0.4, alpha=0.85)
    ax.axvline(np.median(accepted_params[:, i]),
               color="black", linestyle="--", linewidth=1.5, label="median")
    ax.set_title(f"Posterior of {param_names[i]}", fontsize=13)
    ax.set_xlabel("Parameter value", fontsize=11)
    ax.set_ylabel("Count", fontsize=11)
    ax.legend(fontsize=10)

plt.suptitle("ABC Posterior Distributions (Numba-accelerated)", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

##ABC Run 1 Plots

# Convert accepted samples to a DataFrame for easier labeling
df_posterior = pd.DataFrame(accepted_params, columns=[r'$\beta$', r'$\gamma$', r'$\rho$'])

# Create the pairwise plot
plt.figure(figsize=(10, 10))
g = sns.pairplot(
    df_posterior,
    kind='scatter',
    diag_kind='kde', # Smooth density plots on the diagonal
    corner=True,     # Removes the redundant upper triangle
    plot_kws={'alpha': 0.4, 's': 10, 'color': 'midnightblue'},
    diag_kws={'color': 'steelblue', 'fill': True}
)

g.fig.suptitle("Pairwise Posterior Distributions & Correlations", y=1.02, fontsize=16)
plt.show()

##Corner Plot

# Define labels using LaTeX for the plot
labels = [r"$\beta$ (Infection)", r"$\gamma$ (Recovery)", r"$\rho$ (Rewiring)"]

# Generate the corner plot
fig = corner.corner(
    accepted_params,
    labels=labels,
    truths=[np.median(accepted_params[:,0]),
            np.median(accepted_params[:,1]),
            np.median(accepted_params[:,2])], # Mark the medians
    show_titles=True,
    title_fmt=".3f",
    color="darkslategrey",
    fill_contours=True,
    plot_datapoints=True
)

plt.show()

#ABC Run 2
np.random.seed(3247)
# ==============================
# 1. PREPROCESS DATA (Unchanged but using _2 naming for clarity)
# ==============================
obs_inf_2 = infected_df.groupby("time")["infected_fraction"].mean().values
obs_rew_2 = rewire_df.groupby("time")["rewire_count"].mean().values
obs_deg_2 = degree_df.groupby("degree")["count"].mean().values

# ==============================
# 2. UPDATED SUMMARY STATISTICS (5 stats)
# ==============================
def compute_summary_2(inf_vec, rew_vec, deg_hist_vec):
    time_peak = np.argmax(inf_vec).astype(float)
    final_inf = inf_vec[-1]
    auc       = np.sum(inf_vec)
    total_rew = float(np.sum(rew_vec))
    num_isolates = deg_hist_vec[0]

    return np.array([time_peak, final_inf, auc, total_rew, num_isolates])

# Calculate observed summary using the NEW function
obs_summary_2 = compute_summary_2(obs_inf_2, obs_rew_2, obs_deg_2)

# ==============================
# 3. ABC WORKER 2
# ==============================
def abc_worker_2(seed):
    rng = np.random.default_rng(seed)

    beta  = rng.uniform(0.05, 0.50)
    gamma = rng.uniform(0.02, 0.20)
    rho   = rng.uniform(0.00, 0.80)

    sim_inf, sim_rew, sim_deg = simulate(beta, gamma, rho, rng=rng)


    sim_sum = compute_summary_2(sim_inf, sim_rew, sim_deg)

    return [beta, gamma, rho, *sim_sum]

# ==============================
# 4. RUN PARALLEL ABC 2
# ==============================
N_SAMPLES    = 100_000
ACCEPT_RATIO = 0.01

print(f"Starting ABC Run 2: {N_SAMPLES:,} simulations...")
seeds_2 = np.random.randint(0, 2**31, size=N_SAMPLES)

results_raw_2 = Parallel(n_jobs=-1, verbose=5)(
    delayed(abc_worker_2)(s) for s in seeds_2
)

results_raw_2       = np.array(results_raw_2)
all_params_2        = results_raw_2[:, :3]
all_sim_summaries_2 = results_raw_2[:, 3:]

# ==============================
# 5. STANDARDISED DISTANCE 2
# ==============================
stat_scales_2 = np.std(all_sim_summaries_2, axis=0)
stat_scales_2[stat_scales_2 == 0] = 1.0


diffs_2     = (all_sim_summaries_2 - obs_summary_2) / stat_scales_2
distances_2 = np.sqrt(np.sum(diffs_2**2, axis=1))

# ==============================
# 6. SELECTION 2
# ==============================
k_2               = int(ACCEPT_RATIO * N_SAMPLES)
sorted_indices_2  = np.argsort(distances_2)
accepted_idx_2    = sorted_indices_2[:k_2]
accepted_params_2 = all_params_2[accepted_idx_2]

print(f"\nAccepted {len(accepted_params_2):,} samples.")
print(f"Best distance : {distances_2[sorted_indices_2[0]]:.4f}")

# ==============================
# 7. PLOT POSTERIORS 2
# ==============================
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
param_names = ["β (beta)", "γ (gamma)", "ρ (rho)"]
colors      = ["steelblue", "coral", "mediumseagreen"]

for i in range(3):
    ax = axes[i]
    data = accepted_params_2[:, i]
    med = np.median(data)

    ax.hist(data, bins=40, color=colors[i], edgecolor="white", alpha=0.85)
    ax.axvline(med, color="black", linestyle="--", linewidth=1.5, label=f"median: {med:.3f}")
    ax.set_title(f"Posterior 2: {param_names[i]}", fontsize=13)
    ax.set_xlabel("Value")
    ax.legend()

plt.suptitle("ABC Posterior Distributions - Run 2", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

#ABC Run 2

df_posterior_2 = pd.DataFrame(accepted_params_2, columns=[r'$\beta$', r'$\gamma$', r'$\rho$'])

# Create the pairwise plot
g = sns.pairplot(
    df_posterior_2,
    kind='scatter',
    diag_kind='kde',
    corner=True,
    plot_kws={'alpha': 0.4, 's': 10, 'color': 'midnightblue'},
    diag_kws={'color': 'steelblue', 'fill': True}
)

g.fig.suptitle("Pairwise Posterior Distributions & Correlations (Run 2)", y=1.02, fontsize=16)
plt.show()

# ==============================
# CORNER PLOT (Run 2)
# ==============================
import corner

# Define labels using LaTeX for the plot
labels_2 = [r"$\beta$ (Infection)", r"$\gamma$ (Recovery)", r"$\rho$ (Rewiring)"]

# Generate the corner plot using Run 2 data
fig = corner.corner(
    accepted_params_2,
    labels=labels_2,
    truths=[np.median(accepted_params_2[:, 0]),
            np.median(accepted_params_2[:, 1]),
            np.median(accepted_params_2[:, 2])], # Mark the medians for Run 2
    show_titles=True,
    title_fmt=".3f",
    color="darkslategrey",
    fill_contours=True,
    plot_datapoints=True,
    truth_color="red" # Makes the median 'truth' lines stand out
)


fig.suptitle("Corner Plot - ABC Run 2: Parameter Identification", y=1.08, fontsize=16)

plt.show()

# =========================
# 5. ABC-SMC LOOP (ADAPTIVE)
# =========================
# Custom schedule: keep top 50%, then 30%, 15%, 8%, and finally 5%
epsilon_schedule = [50, 30, 15, 8, 5]
epsilon = None

for t in range(N_STEPS):

    # A. RESAMPLE based on weights from the previous generation
    rng_resample = np.random.default_rng(seed_resample[t])
    idx = rng_resample.choice(np.arange(N_PARTICLES), size=N_PARTICLES, p=weights)
    particles = particles[idx]

    # B. ADAPTIVE PERTURB
    # The search radius shrinks as we get closer to the target (0.5 to the power of t)
    # This prevents particles from jumping out of a high-likelihood region once found.
    scale_t = max(0.007, 0.02 * (0.7 ** t))
    particles_prop = np.zeros_like(particles)

    for i in range(N_PARTICLES):
        rng_p = np.random.default_rng(seed_perturb[t, i])
        # Random walk with shrinking variance
        particles_prop[i] = particles[i] + rng_p.normal(0, scale_t, size=3)

        # Boundary Enforcement (Prior constraints)
        particles_prop[i][0] = np.clip(particles_prop[i][0], 0.05, 0.50) # Beta
        particles_prop[i][1] = np.clip(particles_prop[i][1], 0.02, 0.20) # Gamma
        particles_prop[i][2] = np.clip(particles_prop[i][2], 0.0, 0.8)   # Rho

    # C. SIMULATION
    summaries = np.zeros((N_PARTICLES, len(obs_summary_2)))
    for i in range(N_PARTICLES):
        beta, gamma, rho = particles_prop[i]
        sim_inf, sim_rew, sim_deg = simulate(beta, gamma, rho,
                                             rng=np.random.default_rng(seed_sim[t, i]))
        summaries[i] = compute_summary_2(sim_inf, sim_rew, sim_deg)

    # D. DISTANCE (Using Run 2 Standardized Logic)
    diffs = (summaries - obs_summary_2) / stat_scales_2
    dists = np.sqrt(np.sum(diffs**2, axis=1))

    # E. EPSILON UPDATE
    # Based on the percentile schedule defined above
    epsilon = np.percentile(dists, epsilon_schedule[t])

    # F. HARD + SOFT WEIGHTING
    # Hard threshold: particles above epsilon get weight 0
    mask = dists <= epsilon

    # Soft threshold: among the survivors, those closer to the target get higher weight
    kernel_weights = np.exp(-0.5 * (dists / epsilon)**2)
    kernel_weights[~mask] = 0.0

    # Guard against numerical issues if epsilon is extremely small
    if np.sum(kernel_weights) == 0:
        kernel_weights = mask.astype(float)

    # Normalize weights for the next generation
    weights = kernel_weights / np.sum(kernel_weights)

    # Propagate the perturbed particles to the next step
    particles = particles_prop.copy()

    # Calculate ESS to check for particle collapse
    ess = 1 / np.sum(weights**2)
    print(f"SMC Step {t+1}/{N_STEPS} | Epsilon: {epsilon:.4f} | ESS: {ess:.1f} | Mean Dist: {np.mean(dists):.4f}")

# =========================
# 6. FINAL POSTERIOR
# =========================
rng_final = np.random.default_rng(999)
final_idx = rng_final.choice(np.arange(N_PARTICLES), size=N_PARTICLES, p=weights)
posterior_smc = particles[final_idx]

print("\nAdaptive SMC-ABC Complete.")

# ==============================================================
# Final Adaptive SMC-ABC vs. ABC Run 2 Rejection Overlay
# ==============================================================

# 'accepted_params_2' -> Baseline (Run 2 Rejection)
# 'posterior_smc'     -> Final refined particles from Adaptive SMC

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
titles = [r"$\beta$ (Transmission)", r"$\gamma$ (Recovery)", r"$\rho$ (Rewiring)"]
colors_smc = ['dodgerblue', 'orangered', 'forestgreen']

for i in range(3):
    ax = axes[i]

    # 1. Overlay ABC Run 2 Rejection (Baseline)

    sns.histplot(accepted_params_2[:, i],
                 bins=40,
                 kde=False,
                 ax=ax,
                 color='gray',
                 label='ABC Rejection (Run 2)',
                 alpha=0.2,
                 stat="density")

    # 2. Plot Adaptive SMC-ABC Results

    sns.histplot(posterior_smc[:, i],
                 bins=30,
                 kde=True,
                 ax=ax,
                 color=colors_smc[i],
                 edgecolor='white',
                 alpha=0.7,
                 label='Adaptive SMC-ABC',
                 stat="density")

    # 3. Add Median line for the SMC result
    smc_median = np.median(posterior_smc[:, i])
    ax.axvline(smc_median, color='black', linestyle='--', linewidth=2,
               label=f'SMC Median: {smc_median:.3f}')

    # Formatting
    ax.set_title(titles[i], fontsize=14, fontweight='bold')
    ax.set_xlabel("Parameter Value")
    ax.set_ylabel("Density")
    ax.legend(fontsize=9, loc='upper right')

plt.suptitle("Posterior Refinement: Adaptive SMC-ABC vs. Rejection ABC (Run 2)",
             fontsize=16, y=1.05, fontweight='bold')
plt.tight_layout()
plt.show()

# ==============================
# REGRESSION ADJUSTMENT - RUN 2
# ==============================

def apply_regression_adjustment_2(accepted_params, accepted_summaries, obs_summary):
    """
    Adjusts the accepted parameters from Run 2 using local linear regression.
    """
    adjusted_params = np.zeros_like(accepted_params)

    # Perform a separate regression for each parameter (Beta, Gamma, Rho)
    for i in range(accepted_params.shape[1]):
        # Features: The difference between simulated stats and observed stats
        X = accepted_summaries - obs_summary
        y = accepted_params[:, i]

        # Fit the model
        model = LinearRegression().fit(X, y)

        # The adjustment:
        # We find what the model predicts the parameter should be when X = 0 (perfect match)
        # and then add the residuals (the part the model couldn't explain).
        prediction_at_target = model.predict(np.zeros((1, X.shape[1])))
        residuals = y - model.predict(X)
        adjusted_params[:, i] = prediction_at_target + residuals

    # Safety: Clip adjusted values to stay within the original prior bounds
    # beta: [0.05, 0.50], gamma: [0.02, 0.20], rho: [0.0, 0.8]
    adjusted_params[:, 0] = np.clip(adjusted_params[:, 0], 0.05, 0.50)
    adjusted_params[:, 1] = np.clip(adjusted_params[:, 1], 0.02, 0.20)
    adjusted_params[:, 2] = np.clip(adjusted_params[:, 2], 0.00, 0.80)

    return adjusted_params

# 1. Extract summaries for the accepted samples from RUN 2
accepted_summaries_2 = all_sim_summaries_2[accepted_idx_2]

# 2. Apply the adjustment using RUN 2 variables
adjusted_params_2 = apply_regression_adjustment_2(
    accepted_params_2,
    accepted_summaries_2,
    obs_summary_2
)

print(f"Regression adjustment for Run 2 complete.")
print(f"New Medians after Adjustment:")
print(f"Beta: {np.median(adjusted_params_2[:,0]):.4f}")
print(f"Gamma: {np.median(adjusted_params_2[:,1]):.4f}")
print(f"Rho: {np.median(adjusted_params_2[:,2]):.4f}")

# ==============================
# 10. PLOT COMPARISON (RUN 2: REJECTION VS REGRESSION)
# ==============================
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
param_names = [r"$\beta$ (beta)", r"$\gamma$ (gamma)", r"$\rho$ (rho)"]
colors_adj = ["steelblue", "coral", "mediumseagreen"]

for i in range(3):
    ax = axes[i]

    # 1. Original Run 2 Rejection Samples (Background)
    sns.histplot(accepted_params_2[:, i],
                 bins=40,
                 alpha=0.3,
                 label="Rejection (Run 2)",
                 color='gray',
                 stat="density",
                 ax=ax)

    # 2. Adjusted Run 2 Samples (Overlay)
    sns.histplot(adjusted_params_2[:, i],
                 bins=40,
                 alpha=0.6,
                 label="Reg. Adjusted",
                 color=colors_adj[i],
                 stat="density",
                 ax=ax)

    # Add a KDE line for the adjusted data to show the smooth posterior shape
    sns.kdeplot(adjusted_params_2[:, i], color=colors_adj[i], ax=ax, linewidth=2)

    # 3. Median line for Adjusted Results
    adj_med = np.median(adjusted_params_2[:, i])
    ax.axvline(adj_med, color="black", linestyle="--", linewidth=1.5,
               label=f"Adj. Median: {adj_med:.3f}")

    ax.set_title(f"Comparison: {param_names[i]}", fontsize=14)
    ax.set_xlabel("Parameter Value")
    ax.set_ylabel("Density")
    ax.legend(fontsize=9)

plt.suptitle("Impact of Regression Adjustment on ABC Run 2 Posteriors", fontsize=16, y=1.02)
plt.tight_layout()
plt.show()

#BOLFI
# ==============================
# 1. DEFINE THE OBJECTIVE (DISTANCE)
# =============================
np.random.seed(3247)
def objective(params):
    """
    BO passes params as a list: [beta, gamma, rho].
    Returns the distance (to be MINIMIZED).
    """
    beta, gamma, rho = params

    # Run one simulation
    sim_inf, sim_rew, sim_deg = simulate(beta, gamma, rho)
    sim_sum = compute_summary_2(sim_inf, sim_rew, sim_deg)

    # Calculate standardized distance

    diff = (sim_sum - obs_summary_2) / stat_scales_2
    dist = np.sqrt(np.sum(diff**2))

    return dist

# ==============================
# 2. SETUP THE OPTIMIZER
# ==============================
# Define parameter bounds
search_space = [
    (0.05, 0.50), # beta
    (0.02, 0.20), # gamma
    (0.0, 0.8)    # rho
]

# Use a Matern kernel for the Gaussian Process (flexible for noisy simulators)
gp = GaussianProcessRegressor(
    kernel=Matern(nu=2.5),
    alpha=1e-6,
    normalize_y=True,
    noise="gaussian",
    n_restarts_optimizer=5
)

opt = Optimizer(
    dimensions=search_space,
    base_estimator=gp,
    n_initial_points=20,  # Random starts to get a baseline
    acq_func="EI",        # Expected Improvement
)

# ==============================
# 3. RUN THE OPTIMIZATION LOOP
# ==============================
n_iterations = 200

print(f"Running Bayesian Optimization for {n_iterations} iterations...")

for i in range(n_iterations):
    next_theta = opt.ask()            # BO suggests next parameters
    f_val = objective(next_theta)     # Run simulation
    opt.tell(next_theta, f_val)       # Feed result back to GP

    if (i+1) % 20 == 0:
        print(f"Iteration {i+1}: Best distance found so far: {min(opt.yi):.4f}")

# ==============================
# 4. RESULTS
# ==============================
best_index = np.argmin(opt.yi)
best_params = opt.Xi[best_index]
best_distance = opt.yi[best_index]

print(f"\nBest Parameters Found:")
print(f"Beta:  {best_params[0]:.4f}")
print(f"Gamma: {best_params[1]:.4f}")
print(f"Rho:   {best_params[2]:.4f}")
print(f"Best Distance: {best_distance:.4f}")

#Bolfi Plot

# Get the cumulative minimum distance found at each step
mins = np.minimum.accumulate(opt.yi)

plt.figure(figsize=(8, 5))
plt.plot(range(len(opt.yi)), opt.yi, 'o', alpha=0.4, label='Evaluations', color='gray')
plt.plot(range(len(opt.yi)), mins, 'r-', linewidth=2, label='Best Distance')
plt.xlabel("Iteration Number")
plt.ylabel("Distance (Error)")
plt.title("Bayesian Optimization Convergence")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()
